stages:
  - build
  - deploy

build:
  image: docker:25.0.3
  services: 
    - docker:25.0.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploy to production"
