name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:25.0.3-dind
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get install -y make

    - name: Log in to Docker registry
      env:
        DOCKER_USER: ${{ secrets.CI_REGISTRY_USER }}
        DOCKER_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.CI_REGISTRY }}
      run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin

    - name: Build Docker image
      run: make build

    - name: Push Docker image
      run: make push

  tag_prod:
    runs-on: ubuntu-latest
    needs: docker_build

    services:
      docker:
        image: docker:25.0.3-dind
        options: --privileged

    if: startsWith(github.ref, 'refs/tags')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get install -y make

    - name: Log in to Docker registry
      env:
        DOCKER_USER: ${{ secrets.CI_REGISTRY_USER }}
        DOCKER_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.CI_REGISTRY }}
      run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin

    - name: Tag Docker image for production
      run: make tag-prod
