name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:25.0.3-dind
        options: --privileged

    env:
      DOCKER_TLS_CERTDIR: "/certs"
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
      CI_REGISTRY: ${{ secrets.CI_REGISTRY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get install -y make

    - name: Log in to Docker registry
      run: echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

    - name: Build Docker image
      run: make build

    - name: Push Docker image
      run: make push

  tag_prod:
    runs-on: ubuntu-latest
    needs: docker_build

    services:
      docker:
        image: docker:25.0.3-dind
        options: --privileged

    env:
      DOCKER_TLS_CERTDIR: "/certs"
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
      CI_REGISTRY: ${{ secrets.CI_REGISTRY }}

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get install -y make

    - name: Log in to Docker registry
      run: echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

    - name: Tag Docker image for production
      run: make tag-prod
